---
title: "Research"
toc: true
toc-location: right
---

## Work in Progress

**Demand for Advance Payments: Experimental Evidence from India's Brick Kilns**

**Female Wage Labour and Fertility: Evidence from the Cut-Flower Industry in Kenya**
*With Niclas Moneke and Céline Zipfel.*

**Jobs to End Poverty: Evidence from Bangladesh**
*With Oriana Bandiera, Jack Thiemel, Robin Burgess, Stefano Caria and Munshi Sulaiman.*

## Publications

**Distributional and Climate Implications of Policy Responses to the Energy Crisis: Lessons from the UK**
*With Thiemo Fetzer and Ludovica Gazzè.*
*Economic Policy*, 2024, 39(120): 711–756.
[[Published]](https://academic.oup.com/economicpolicy/article/39/120/711/7709888) [[Working Paper]](https://cepr.org/publications/dp17990)


## Book Chapters

**Technology and Development**
*With Robin Burgess and Céline Zipfel.*
In Madon, T., Gadgil, A. J., Anderson, R., Casaburi, L., Lee, K., Rezaee, A. (eds), *Introduction to Development Engineering*. Springer, Cham, 2023.
[[Chapter]](https://link.springer.com/content/pdf/10.1007/978-3-030-86065-3.pdf)
